version: 1.0.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\UPnP.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - .\UPnP\bin\Debug\netstandard2.0\UPnP.dll
after_test:
  - ps: .\UPnP\nuget_pack.ps1
artifacts:
  - path: '*.nupkg'
    name: UPnP nupkg
deploy:
  - provider: GitHub
    auth_token:
      secure: QJoBiqbeg1z+3WRoH1IdXRsnXtvwS95U2Z89JH9DrnEhJYMYbRpKjUmGEbOU3OnDLFz8gKqzP8y7KpL226lCb/Y+W6CTt7EGouenMIKnzZBllZVvSG73LdhHgD8RbxIy
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: VLSz2Mm3RJU7/uhvY1kOSfewPUL43YB7sxMOadvqUyrIFcU2DV2S84mtuySIJJX0
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
